package config

const (
    NUMBER_OF_RANDOM_CLASSIFIERS = 10
    USE_RANDOM_WEAK_CLASSIFIERS = false
    INCORPORATE_COST_SENSITIVE_LEARNING = true
    USE_THRESHOLD_CLASSIFICATION = true
    TEST_PERCENT = 0.4
    NUM_OF_WEAK_CLASSIFIERS = 100
    OVER_SAMPLING_TRAINING_SET = false
)